review:
  security: true
  correctness: true
  performance: true
  style: true
  edge_cases: true
  review:
  paths:
    exclude:
      - vendor/**
      - vendor-static/**
      - modules/**/vendor/**
      - modules/**/vendor-static/**

assumptions:
  - Code runs within WHMCS client and admin areas
  - PHP version is >= 8.1
  